// Author (byline) slugs that are the same person or source spelled
// inconsistently. Generated by `yarn sitemap audit-authors --write` from the
// live byline taxonomy and then reviewed by hand — it is safe to edit.
//
// Effects: alias slugs are excluded from sitemap-authors.xml, /author/<alias>
// redirects (301) to /author/<canonical>, and the canonical author page lists
// articles from every byline in the group. Merging the terms in WordPress
// itself is still the real fix; see docs/author-merge-report.md.
import type { AuthorAliasData } from '../lib/sitemap/types.ts'

export const authorAliases: AuthorAliasData = {
  "version": 1,
  "generatedAt": "2026-09-15T08:38:44.745Z",
  "groups": [
    {
      "canonical": "igihe",
      "canonicalId": 170,
      "name": "IGIHE",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "igi9he",
          "id": 2439,
          "name": "IGI9HE",
          "count": 1
        }
      ]
    },
    {
      "canonical": "theophile-niyitegeka",
      "canonicalId": 160,
      "name": "Théophile Niyitegeka",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "theophile-niyiyegeka",
          "id": 2582,
          "name": "Théophile Niyiyegeka",
          "count": 1
        }
      ]
    },
    {
      "canonical": "al-jazeera",
      "canonicalId": 2474,
      "name": "AL JAZEERA",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "aljazeera",
          "id": 2473,
          "name": "ALJAZEERA",
          "count": 5
        },
        {
          "slug": "al-azeera",
          "id": 2495,
          "name": "AL AZEERA",
          "count": 2
        },
        {
          "slug": "al-jazeeera",
          "id": 2578,
          "name": "Al Jazeeera",
          "count": 2
        },
        {
          "slug": "al-j-azeera",
          "id": 2511,
          "name": "AL J AZEERA",
          "count": 1
        },
        {
          "slug": "al-jaazeera",
          "id": 2581,
          "name": "Al Jaazeera",
          "count": 1
        },
        {
          "slug": "al-jazeer",
          "id": 2484,
          "name": "AL JAZEER",
          "count": 1
        },
        {
          "slug": "al-jazeera-3",
          "id": 2551,
          "name": "Al Jazeera:",
          "count": 1
        },
        {
          "slug": "al-jjazeera",
          "id": 2519,
          "name": "Al Jjazeera",
          "count": 1
        },
        {
          "slug": "al-jzeera",
          "id": 2521,
          "name": "Al Jzeera",
          "count": 1
        }
      ]
    },
    {
      "canonical": "igihe-reporter",
      "canonicalId": 334,
      "name": "IGIHE Reporter",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "igihe-repeorter",
          "id": 2370,
          "name": "IGIHE Repeorter",
          "count": 1
        },
        {
          "slug": "igihe-reporte",
          "id": 2270,
          "name": "IGIHE Reporte",
          "count": 1
        }
      ]
    },
    {
      "canonical": "wycliffe-nyamasege",
      "canonicalId": 192,
      "name": "Wycliffe Nyamasege",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "wycliffe-nyamasenge",
          "id": 3164,
          "name": "Wycliffe Nyamasenge",
          "count": 1
        }
      ]
    },
    {
      "canonical": "science-daily",
      "canonicalId": 2491,
      "name": "SCIENCE DAILY",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "sciencedaily",
          "id": 2525,
          "name": "Sciencedaily",
          "count": 2
        }
      ]
    },
    {
      "canonical": "daily-nation",
      "canonicalId": 2461,
      "name": "Daily Nation",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dailynation",
          "id": 2663,
          "name": "DailyNation",
          "count": 1
        }
      ]
    },
    {
      "canonical": "dusabemungu-ange-de-la-victoire",
      "canonicalId": 474,
      "name": "Dusabemungu Ange de la Victoire",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "ange-de-la-victoire-dusabemungu",
          "id": 518,
          "name": "Ange de la Victoire Dusabemungu",
          "count": 155
        },
        {
          "slug": "dusabemungu-ange-de-la-vicotire",
          "id": 540,
          "name": "Dusabemungu Ange De La Vicotire",
          "count": 2
        },
        {
          "slug": "dusabemungu-ange-de-la-vicotoire",
          "id": 513,
          "name": "Dusabemungu Ange De La Vicotoire",
          "count": 2
        },
        {
          "slug": "dusabemungu-ange-de-l-victoire",
          "id": 565,
          "name": "Dusabemungu Ange De L Victoire",
          "count": 1
        }
      ]
    },
    {
      "canonical": "esther-muhozi",
      "canonicalId": 3112,
      "name": "Esther Muhozi",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "esther-muhoozi",
          "id": 3129,
          "name": "Esther Muhoozi",
          "count": 2
        },
        {
          "slug": "esher-muhozi",
          "id": 3128,
          "name": "Esher Muhozi",
          "count": 1
        },
        {
          "slug": "muhozi-esther",
          "id": 166,
          "name": "Muhozi Esther",
          "count": 1
        }
      ]
    },
    {
      "canonical": "daily-news",
      "canonicalId": 2476,
      "name": "DAILY NEWS",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "daily-news-3",
          "id": 2520,
          "name": "Daily News:",
          "count": 2
        }
      ]
    },
    {
      "canonical": "daily-monitor",
      "canonicalId": 2481,
      "name": "DAILY MONITOR",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "daily-monityor",
          "id": 2503,
          "name": "DAILY MONITYOR",
          "count": 1
        },
        {
          "slug": "dailymonitor",
          "id": 2912,
          "name": "DailyMonitor",
          "count": 1
        }
      ]
    },
    {
      "canonical": "nicole-kamanzi-m",
      "canonicalId": 2942,
      "name": "Nicole Kamanzi M.",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "nicole-kamanzi-m-3",
          "id": 2944,
          "name": "Nicole Kamanzi M",
          "count": 3
        },
        {
          "slug": "nicol-kamanzi-m",
          "id": 2972,
          "name": "Nicol Kamanzi M.",
          "count": 1
        },
        {
          "slug": "nicole-kmanzi-m",
          "id": 2969,
          "name": "Nicole Kmanzi M.",
          "count": 1
        }
      ]
    },
    {
      "canonical": "elina-jonas-ruzindaza",
      "canonicalId": 204,
      "name": "Elina Jonas Ruzindaza",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "elina-jonas-ruzindana",
          "id": 2959,
          "name": "Elina Jonas Ruzindana",
          "count": 11
        },
        {
          "slug": "elina-jonas-ruzundaza",
          "id": 2961,
          "name": "Elina Jonas Ruzundaza",
          "count": 2
        },
        {
          "slug": "elina-jonnas-ruzindaza",
          "id": 2962,
          "name": "Elina Jonnas Ruzindaza",
          "count": 1
        },
        {
          "slug": "elinajonas-ruzindana",
          "id": 2960,
          "name": "ElinaJonas Ruzindana",
          "count": 1
        }
      ]
    },
    {
      "canonical": "sam-k-nkurunziza-2",
      "canonicalId": 3135,
      "name": "Sam K Nkurunziza",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "by-sam-k-nkurunziza",
          "id": 3137,
          "name": "By Sam K Nkurunziza",
          "count": 2
        },
        {
          "slug": "sam-k-nurunziza",
          "id": 3139,
          "name": "Sam K Nurunziza",
          "count": 2
        },
        {
          "slug": "sam-k-nkurunziza",
          "id": 169,
          "name": "Sam K. Nkurunziza",
          "count": 1
        },
        {
          "slug": "sam-k-nkururnziza",
          "id": 3177,
          "name": "Sam K Nkururnziza",
          "count": 1
        }
      ]
    },
    {
      "canonical": "karirima-aimable-ngarambe",
      "canonicalId": 269,
      "name": "Karirima Aimable Ngarambe",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "aimable-karirima-ngarambe",
          "id": 2614,
          "name": "Aimable Karirima Ngarambe",
          "count": 2
        },
        {
          "slug": "karirima-ngarambe-aimable",
          "id": 2369,
          "name": "Karirima Ngarambe Aimable",
          "count": 2
        }
      ]
    },
    {
      "canonical": "ange-de-la-victoire-d",
      "canonicalId": 2277,
      "name": "Ange de la Victoire D.",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "ange-de-la-victoire",
          "id": 2280,
          "name": "Ange de la Victoire",
          "count": 7
        },
        {
          "slug": "ange-de-la-vctoire-d",
          "id": 2445,
          "name": "Ange de la Vctoire D.",
          "count": 1
        },
        {
          "slug": "ange-de-la-victoire-d-3",
          "id": 2432,
          "name": "Ange de la Victoire. D",
          "count": 1
        }
      ]
    },
    {
      "canonical": "zaninka-umutesi",
      "canonicalId": 3072,
      "name": "Zaninka Umutesi",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "zaninka-mutesi",
          "id": 3073,
          "name": "Zaninka Mutesi",
          "count": 2
        },
        {
          "slug": "zanika-umutesi",
          "id": 3075,
          "name": "Zanika Umutesi",
          "count": 1
        }
      ]
    },
    {
      "canonical": "jean-damour-mugabo-3",
      "canonicalId": 2813,
      "name": "Jean d’Amour Mugabo",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "jean-damour-mugabo",
          "id": 195,
          "name": "Jean d'Amour Mugabo",
          "count": 26
        },
        {
          "slug": "mugabo-jean-damour",
          "id": 2829,
          "name": "Mugabo Jean d'Amour",
          "count": 3
        },
        {
          "slug": "by-jean-damour-mugabo",
          "id": 2812,
          "name": "By Jean d’Amour Mugabo",
          "count": 1
        },
        {
          "slug": "mugabo-jean-damour-3",
          "id": 2838,
          "name": "Mugabo Jean d’Amour",
          "count": 1
        }
      ]
    },
    {
      "canonical": "news-24",
      "canonicalId": 2462,
      "name": "News 24",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "news24",
          "id": 2459,
          "name": "News24",
          "count": 2
        }
      ]
    },
    {
      "canonical": "karirima-a-ngarambe-8",
      "canonicalId": 2285,
      "name": "Karirima A. Ngarambe",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "karirima-a-ngarambe",
          "id": 480,
          "name": "Karirima A .Ngarambe",
          "count": 24
        },
        {
          "slug": "karirima-a-ngarambe-2",
          "id": 577,
          "name": "Karirima A.Ngarambe",
          "count": 4
        },
        {
          "slug": "karirima-ngarambe",
          "id": 693,
          "name": "Karirima Ngarambe",
          "count": 4
        },
        {
          "slug": "karirima-a-ngarambe-3",
          "id": 592,
          "name": "Karirima A Ngarambe",
          "count": 2
        },
        {
          "slug": "karirima-a-ngarambe-9",
          "id": 3167,
          "name": "Karirima. A. Ngarambe",
          "count": 1
        },
        {
          "slug": "karirima-ngarambe-a",
          "id": 3165,
          "name": "Karirima Ngarambe A",
          "count": 1
        },
        {
          "slug": "karirima-ngarambe-a-3",
          "id": 3173,
          "name": "Karirima Ngarambe A.",
          "count": 1
        },
        {
          "slug": "karirina-a-ngarambe",
          "id": 2283,
          "name": "Karirina A. Ngarambe",
          "count": 1
        },
        {
          "slug": "ngarambe-a-karirima",
          "id": 3170,
          "name": "Ngarambe A. Karirima",
          "count": 1
        }
      ]
    },
    {
      "canonical": "joram-muhoozi",
      "canonicalId": 278,
      "name": "Joram Muhoozi",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "joram-muhooza",
          "id": 287,
          "name": "Joram Muhooza",
          "count": 3
        },
        {
          "slug": "joram-muhozi",
          "id": 344,
          "name": "Joram Muhozi",
          "count": 1
        }
      ]
    },
    {
      "canonical": "the-new-vision",
      "canonicalId": 2465,
      "name": "The New Vision",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "the-new-vision-3",
          "id": 2510,
          "name": "THE NEW VISION:",
          "count": 1
        }
      ]
    },
    {
      "canonical": "alain-jules-hirwa",
      "canonicalId": 236,
      "name": "Alain Jules Hirwa",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "alain-jule-hirwa",
          "id": 2955,
          "name": "Alain Jule Hirwa",
          "count": 1
        }
      ]
    },
    {
      "canonical": "the-east-african",
      "canonicalId": 2460,
      "name": "The East African",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "the-eastafrican",
          "id": 2902,
          "name": "The EastAfrican",
          "count": 2
        }
      ]
    },
    {
      "canonical": "jean-damour-nsabimana-2",
      "canonicalId": 383,
      "name": "Jean d'Amour NSABIMANA",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "jean-damour-nsabimana",
          "id": 382,
          "name": "Jean d’Amour NSABIMANA",
          "count": 21
        },
        {
          "slug": "nsabimana-jean-damour",
          "id": 384,
          "name": "Nsabimana Jean Damour",
          "count": 12
        },
        {
          "slug": "jean-damour-nsabiamana",
          "id": 399,
          "name": "Jean d’Amour Nsabiamana",
          "count": 1
        },
        {
          "slug": "nsabimana-jean-damour-2",
          "id": 394,
          "name": "Nsabimana Jean D'amour",
          "count": 1
        }
      ]
    },
    {
      "canonical": "christian-mugisha",
      "canonicalId": 2252,
      "name": "Christian Mugisha",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "mugisha-christian",
          "id": 3188,
          "name": "Mugisha Christian",
          "count": 7
        }
      ]
    },
    {
      "canonical": "kalinda-brendah",
      "canonicalId": 2402,
      "name": "Kalinda Brendah",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "brendah-kalinda",
          "id": 2443,
          "name": "Brendah Kalinda",
          "count": 3
        },
        {
          "slug": "kalinda-brenda",
          "id": 2403,
          "name": "Kalinda Brenda",
          "count": 3
        }
      ]
    },
    {
      "canonical": "the-guardian",
      "canonicalId": 234,
      "name": "The Guardian",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "theguardian",
          "id": 2876,
          "name": "THEGUARDIAN",
          "count": 2
        },
        {
          "slug": "the-guradian",
          "id": 2877,
          "name": "The Guradian",
          "count": 1
        }
      ]
    },
    {
      "canonical": "ndahiro-herbert",
      "canonicalId": 330,
      "name": "Ndahiro Herbert",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "herbert-ndahiro",
          "id": 342,
          "name": "Herbert Ndahiro",
          "count": 20
        }
      ]
    },
    {
      "canonical": "magnifique-migisha",
      "canonicalId": 318,
      "name": "Magnifique Migisha",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "migisha-magnifique",
          "id": 376,
          "name": "MIGISHA Magnifique",
          "count": 9
        },
        {
          "slug": "migisha-manifique",
          "id": 371,
          "name": "Migisha Manifique",
          "count": 1
        }
      ]
    },
    {
      "canonical": "nzohabonimana-daniel",
      "canonicalId": 583,
      "name": "Nzohabonimana Daniel",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "daniel-nzohabonimana",
          "id": 538,
          "name": "Daniel Nzohabonimana",
          "count": 8
        }
      ]
    },
    {
      "canonical": "olga-i-ishimwe",
      "canonicalId": 196,
      "name": "Olga I. Ishimwe",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "olga-ishimwe",
          "id": 2846,
          "name": "Olga Ishimwe",
          "count": 20
        }
      ]
    },
    {
      "canonical": "prof-nshuti-manasseh",
      "canonicalId": 587,
      "name": "Prof. Nshuti Manasseh",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "nshuti-manasseh",
          "id": 2407,
          "name": "Nshuti Manasseh",
          "count": 2
        },
        {
          "slug": "prof-manasseh-nshuti",
          "id": 2434,
          "name": "Prof. Manasseh Nshuti",
          "count": 1
        },
        {
          "slug": "prof-nshuti-manasseh-3",
          "id": 644,
          "name": "Prof.Nshuti Manasseh",
          "count": 1
        },
        {
          "slug": "prof-nshuti-manasseh-2",
          "id": 616,
          "name": "Prof. Nshuti Manasseh.",
          "count": 0
        }
      ]
    },
    {
      "canonical": "dr-bizimana-jean-damascene",
      "canonicalId": 203,
      "name": "Dr. BIZIMANA Jean Damascene",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dr-bizimana-jean-damascene-7",
          "id": 2957,
          "name": "Dr. Bizimana Jean-Damascène",
          "count": 4
        },
        {
          "slug": "bizimana-jean-damascene",
          "id": 2816,
          "name": "Bizimana Jean Damascene",
          "count": 1
        },
        {
          "slug": "dr-bizimana-jean-damascene-6",
          "id": 2767,
          "name": "Dr BIZIMANA Jean Damascène",
          "count": 1
        },
        {
          "slug": "dr-jean-damascene-bizimana",
          "id": 2703,
          "name": "Dr. Jean-Damascène Bizimana",
          "count": 1
        }
      ]
    },
    {
      "canonical": "elisee-mpirwa",
      "canonicalId": 339,
      "name": "Elisée Mpirwa",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "elise-mpirwa",
          "id": 528,
          "name": "ELise Mpirwa",
          "count": 1
        },
        {
          "slug": "elysee-mpirwa",
          "id": 501,
          "name": "Elysee Mpirwa",
          "count": 1
        }
      ]
    },
    {
      "canonical": "abraham-rumanzi",
      "canonicalId": 294,
      "name": "Abraham Rumanzi",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "abraham-r-rumanzi",
          "id": 307,
          "name": "Abraham R. Rumanzi",
          "count": 2
        }
      ]
    },
    {
      "canonical": "abc-news",
      "canonicalId": 2516,
      "name": "ABC News",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "abc-news-3",
          "id": 2564,
          "name": "ABC NEWS:",
          "count": 1
        }
      ]
    },
    {
      "canonical": "gasana-fiona",
      "canonicalId": 405,
      "name": "Gasana Fiona",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "fiona-gasana",
          "id": 274,
          "name": "Fiona Gasana",
          "count": 18
        }
      ]
    },
    {
      "canonical": "diana-mutimura",
      "canonicalId": 281,
      "name": "Diana Mutimura",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "dianah-mutimura",
          "id": 275,
          "name": "Dianah Mutimura",
          "count": 4
        }
      ]
    },
    {
      "canonical": "fox-news",
      "canonicalId": 2524,
      "name": "Fox News",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "foxnews",
          "id": 2945,
          "name": "FoxNews",
          "count": 1
        }
      ]
    },
    {
      "canonical": "un-news-centre",
      "canonicalId": 2611,
      "name": "UN News Centre",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "un-news-center",
          "id": 2550,
          "name": "UN News Center",
          "count": 6
        }
      ]
    },
    {
      "canonical": "olivier-rubibi",
      "canonicalId": 436,
      "name": "Olivier RUBIBI",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "oliveir-rubibi",
          "id": 572,
          "name": "Oliveir Rubibi",
          "count": 4
        },
        {
          "slug": "rubibi-olivier",
          "id": 662,
          "name": "Rubibi Olivier",
          "count": 3
        },
        {
          "slug": "oliver-rubibi",
          "id": 446,
          "name": "Oliver Rubibi",
          "count": 2
        }
      ]
    },
    {
      "canonical": "eve-musagara",
      "canonicalId": 402,
      "name": "Eve Musagara",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "musagara-eve",
          "id": 416,
          "name": "Musagara Eve",
          "count": 1
        }
      ]
    },
    {
      "canonical": "relief-web",
      "canonicalId": 2698,
      "name": "Relief Web",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "reliefweb",
          "id": 2689,
          "name": "Reliefweb",
          "count": 1
        }
      ]
    },
    {
      "canonical": "christian-bizimana",
      "canonicalId": 276,
      "name": "Christian Bizimana",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "chrisitan-bizimana",
          "id": 285,
          "name": "Chrisitan Bizimana",
          "count": 1
        }
      ]
    },
    {
      "canonical": "deus-ntakirutimana",
      "canonicalId": 484,
      "name": "Deus Ntakirutimana",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ntakirutimana-deus",
          "id": 676,
          "name": "Ntakirutimana Deus",
          "count": 2
        }
      ]
    },
    {
      "canonical": "wang-xuekun",
      "canonicalId": 3067,
      "name": "WANG Xuekun",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "amb-wang-xuekun",
          "id": 3133,
          "name": "Amb. WANG Xuekun",
          "count": 2
        }
      ]
    },
    {
      "canonical": "the-citizen",
      "canonicalId": 2636,
      "name": "The Citizen",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "thecitizen",
          "id": 2868,
          "name": "Thecitizen",
          "count": 1
        }
      ]
    },
    {
      "canonical": "dusi-blaise",
      "canonicalId": 417,
      "name": "Dusi Blaise",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "blaise-dusi",
          "id": 420,
          "name": "Blaise Dusi",
          "count": 1
        }
      ]
    },
    {
      "canonical": "emmanuel-kanamugire",
      "canonicalId": 494,
      "name": "Emmanuel Kanamugire",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "kanamugire-emmanuel",
          "id": 3007,
          "name": "Kanamugire Emmanuel",
          "count": 4
        }
      ]
    },
    {
      "canonical": "olivier-muhirwa",
      "canonicalId": 377,
      "name": "Olivier MUHIRWA",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "oliveir-muhirwa",
          "id": 456,
          "name": "Oliveir Muhirwa",
          "count": 4
        },
        {
          "slug": "muhirwa-olivier",
          "id": 443,
          "name": "Muhirwa Olivier",
          "count": 2
        }
      ]
    },
    {
      "canonical": "jean-claude-ntawitonda",
      "canonicalId": 624,
      "name": "Jean Claude Ntawitonda",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ntawitonda-jean-claude",
          "id": 700,
          "name": "Ntawitonda Jean Claude",
          "count": 1
        }
      ]
    },
    {
      "canonical": "joram-muhoozi-agencies-2",
      "canonicalId": 336,
      "name": "Joram Muhoozi &amp; Agencies",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "joram-muhoozi-agencies",
          "id": 329,
          "name": "Joram Muhoozi &amp;Agencies",
          "count": 2
        },
        {
          "slug": "joram-muhoozi-agencies-3",
          "id": 341,
          "name": "Joram Muhoozi&amp; Agencies",
          "count": 1
        }
      ]
    },
    {
      "canonical": "jotham-ntirenganya",
      "canonicalId": 452,
      "name": "Jotham Ntirenganya",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "jothan-ntirenganya",
          "id": 499,
          "name": "Jothan Ntirenganya",
          "count": 1
        }
      ]
    },
    {
      "canonical": "serge-iradukunda",
      "canonicalId": 191,
      "name": "Serge Iradukunda",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "iradukunda-serge",
          "id": 3163,
          "name": "Iradukunda Serge",
          "count": 2
        }
      ]
    },
    {
      "canonical": "alex-twahirwa",
      "canonicalId": 257,
      "name": "Alex Twahirwa",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "twahirwa-alex",
          "id": 628,
          "name": "Twahirwa Alex",
          "count": 1
        }
      ]
    },
    {
      "canonical": "dr-charles-kiiza",
      "canonicalId": 719,
      "name": "Dr. Charles Kiiza",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "charles-kiiza",
          "id": 3217,
          "name": "Charles Kiiza",
          "count": 1
        }
      ]
    },
    {
      "canonical": "madame-noire",
      "canonicalId": 2496,
      "name": "MADAME NOIRE",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "madame-noire-3",
          "id": 2500,
          "name": "MADAME NOIRE:",
          "count": 1
        }
      ]
    },
    {
      "canonical": "marie-chantal-nyirabera",
      "canonicalId": 461,
      "name": "Marie Chantal Nyirabera",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "nyirabera-marie-chantal",
          "id": 476,
          "name": "Nyirabera Marie Chantal",
          "count": 1
        }
      ]
    },
    {
      "canonical": "tombola-felicie",
      "canonicalId": 2386,
      "name": "Tombola Felicie",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "felicie-tombola",
          "id": 2892,
          "name": "Félicie Tombola",
          "count": 1
        },
        {
          "slug": "tombola-felecie",
          "id": 2452,
          "name": "Tombola Felecie",
          "count": 1
        },
        {
          "slug": "tombola-flicie",
          "id": 2415,
          "name": "Tombola Flicie",
          "count": 1
        }
      ]
    },
    {
      "canonical": "bigabo-patrick",
      "canonicalId": 510,
      "name": "Bigabo Patrick",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "patrick-bigabo",
          "id": 324,
          "name": "Patrick Bigabo",
          "count": 2
        },
        {
          "slug": "bagabo-patrick",
          "id": 328,
          "name": "Bagabo Patrick",
          "count": 1
        }
      ]
    },
    {
      "canonical": "france-24",
      "canonicalId": 244,
      "name": "France 24",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "france24",
          "id": 2954,
          "name": "FRANCE24",
          "count": 1
        }
      ]
    },
    {
      "canonical": "jeannette-kagame",
      "canonicalId": 519,
      "name": "Jeannette Kagame",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "h-e-jeannette-kagame",
          "id": 189,
          "name": "H.E Jeannette Kagame",
          "count": 2
        },
        {
          "slug": "mrs-jeannette-kagame",
          "id": 3091,
          "name": "Mrs Jeannette Kagame",
          "count": 2
        }
      ]
    },
    {
      "canonical": "kwizera-emmanuel",
      "canonicalId": 439,
      "name": "Kwizera Emmanuel",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "emmanuel-kwizera",
          "id": 2409,
          "name": "Emmanuel Kwizera",
          "count": 1
        },
        {
          "slug": "kwizera-emmanueal",
          "id": 453,
          "name": "Kwizera Emmanueal",
          "count": 1
        }
      ]
    },
    {
      "canonical": "lamin-m-manneh",
      "canonicalId": 548,
      "name": "Lamin M. Manneh",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "lamin-m-manneh-2",
          "id": 667,
          "name": "Lamin .M. Manneh",
          "count": 1
        },
        {
          "slug": "lamin-manneh",
          "id": 522,
          "name": "Lamin Manneh",
          "count": 1
        },
        {
          "slug": "mr-lamin-m-manneh",
          "id": 2278,
          "name": "Mr Lamin M. Manneh",
          "count": 1
        }
      ]
    },
    {
      "canonical": "abdou-nyampeta",
      "canonicalId": 463,
      "name": "Abdou Nyampeta",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "abdoul-nyampeta",
          "id": 515,
          "name": "Abdoul Nyampeta",
          "count": 2
        }
      ]
    },
    {
      "canonical": "hakizimana-thamim",
      "canonicalId": 2349,
      "name": "Hakizimana Thamim",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "thamimu-hakizimana",
          "id": 2288,
          "name": "Thamimu Hakizimana",
          "count": 5
        },
        {
          "slug": "thamim-hakizimana",
          "id": 2326,
          "name": "Thamim Hakizimana",
          "count": 4
        },
        {
          "slug": "hakizimana-thamimu",
          "id": 2381,
          "name": "Hakizimana Thamimu",
          "count": 1
        },
        {
          "slug": "tamim-hakizimana",
          "id": 666,
          "name": "Tamim Hakizimana",
          "count": 1
        }
      ]
    },
    {
      "canonical": "maniraguha-ferdinand",
      "canonicalId": 2982,
      "name": "Maniraguha Ferdinand",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ferdinand-maniraguha",
          "id": 220,
          "name": "Ferdinand Maniraguha",
          "count": 3
        }
      ]
    },
    {
      "canonical": "richard-irakoze",
      "canonicalId": 410,
      "name": "Richard Irakoze",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "irakoze-richard",
          "id": 460,
          "name": "IRAKOZE Richard",
          "count": 1
        }
      ]
    },
    {
      "canonical": "rwamapera-kelly",
      "canonicalId": 2323,
      "name": "Rwamapera Kelly",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "kelly-rwamapera",
          "id": 2316,
          "name": "Kelly Rwamapera",
          "count": 1
        }
      ]
    },
    {
      "canonical": "standard-media",
      "canonicalId": 2488,
      "name": "STANDARD MEDIA",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "standardmedia",
          "id": 2863,
          "name": "Standardmedia",
          "count": 1
        }
      ]
    },
    {
      "canonical": "donald-kaberuka",
      "canonicalId": 602,
      "name": "Donald Kaberuka",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dr-donald-kaberuka",
          "id": 643,
          "name": "Dr. Donald Kaberuka",
          "count": 1
        }
      ]
    },
    {
      "canonical": "james-habimana",
      "canonicalId": 490,
      "name": "James Habimana",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "habimana-james",
          "id": 478,
          "name": "Habimana James",
          "count": 1
        }
      ]
    },
    {
      "canonical": "jean-de-dieu-akayezu",
      "canonicalId": 3024,
      "name": "Jean de Dieu Akayezu",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "akayezu-jean-de-dieu",
          "id": 3102,
          "name": "Akayezu Jean de Dieu",
          "count": 1
        }
      ]
    },
    {
      "canonical": "prof-nshuti-mannaseh",
      "canonicalId": 590,
      "name": "Prof. Nshuti Mannaseh",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "prof-mannaseh-nshuti",
          "id": 629,
          "name": "Prof. Mannaseh Nshuti",
          "count": 1
        }
      ]
    },
    {
      "canonical": "virungapost",
      "canonicalId": 2866,
      "name": "VirungaPost",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "virunga-post",
          "id": 2869,
          "name": "Virunga Post",
          "count": 2
        }
      ]
    },
    {
      "canonical": "anadolu-agency",
      "canonicalId": 2454,
      "name": "ANADOLU AGENCY",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "anadolou-agency",
          "id": 2776,
          "name": "Anadolou Agency",
          "count": 1
        }
      ]
    },
    {
      "canonical": "besabesa-m-etienne",
      "canonicalId": 684,
      "name": "Besabesa M. Etienne",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "besabesa-m-etienne-2",
          "id": 689,
          "name": "Besabesa M.Etienne",
          "count": 1
        }
      ]
    },
    {
      "canonical": "chimpreports",
      "canonicalId": 2567,
      "name": "Chimpreports",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "chimp-reports",
          "id": 2600,
          "name": "Chimp Reports",
          "count": 1
        }
      ]
    },
    {
      "canonical": "einat-weiss",
      "canonicalId": 3132,
      "name": "Einat Weiss",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "amb-einat-weiss",
          "id": 3222,
          "name": "Amb. Einat Weiss",
          "count": 1
        }
      ]
    },
    {
      "canonical": "human-rights-watch",
      "canonicalId": 2579,
      "name": "Human Rights Watch",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "human-right-watch",
          "id": 2592,
          "name": "Human Right Watch",
          "count": 1
        }
      ]
    },
    {
      "canonical": "ignatius-r-kabagambe",
      "canonicalId": 2993,
      "name": "Ignatius R. Kabagambe",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "kabagambe-r-ignatius",
          "id": 2998,
          "name": "Kabagambe R. Ignatius",
          "count": 3
        },
        {
          "slug": "ignatius-kabagambe",
          "id": 369,
          "name": "Ignatius Kabagambe",
          "count": 1
        }
      ]
    },
    {
      "canonical": "mohammed-t-yusuf",
      "canonicalId": 345,
      "name": "Mohammed T. Yusuf",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "mohammed-yusuf",
          "id": 351,
          "name": "Mohammed Yusuf",
          "count": 2
        }
      ]
    },
    {
      "canonical": "olivier-kabalisa",
      "canonicalId": 413,
      "name": "Olivier Kabalisa",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "kabalisa-olivier",
          "id": 424,
          "name": "Kabalisa Olivier",
          "count": 1
        }
      ]
    },
    {
      "canonical": "the-standard",
      "canonicalId": 2871,
      "name": "The Standard",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "thestandard",
          "id": 2920,
          "name": "TheStandard",
          "count": 1
        }
      ]
    },
    {
      "canonical": "turikumwe-noel",
      "canonicalId": 471,
      "name": "Turikumwe Noël",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "noel-turikumwe",
          "id": 475,
          "name": "Noël Turikumwe",
          "count": 1
        }
      ]
    },
    {
      "canonical": "africa-news-agency",
      "canonicalId": 2628,
      "name": "Africa News Agency",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "african-news-agency",
          "id": 2839,
          "name": "African News Agency",
          "count": 1
        }
      ]
    },
    {
      "canonical": "alarabiya",
      "canonicalId": 2545,
      "name": "Alarabiya",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "alarabia",
          "id": 2750,
          "name": "Alarabia",
          "count": 1
        }
      ]
    },
    {
      "canonical": "alexia-mpinganzima",
      "canonicalId": 2937,
      "name": "Alexia Mpinganzima",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "mpinganzima-alexia",
          "id": 219,
          "name": "Mpinganzima Alexia",
          "count": 1
        }
      ]
    },
    {
      "canonical": "donald-w-koran",
      "canonicalId": 368,
      "name": "Donald W. Koran",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ambassador-donald-koran",
          "id": 620,
          "name": "Ambassador Donald Koran",
          "count": 1
        },
        {
          "slug": "ambassador-donald-w-koran",
          "id": 387,
          "name": "Ambassador Donald W. Koran",
          "count": 1
        },
        {
          "slug": "donald-koran",
          "id": 2341,
          "name": "Donald Koran",
          "count": 1
        }
      ]
    },
    {
      "canonical": "elina-jonas-r",
      "canonicalId": 2966,
      "name": "Elina Jonas R.",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "elina-jonas",
          "id": 2958,
          "name": "Elina Jonas",
          "count": 1
        }
      ]
    },
    {
      "canonical": "emma-marie-umurerwa",
      "canonicalId": 2295,
      "name": "Emma-Marie Umurerwa",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "emma-marie-umurerwa-5",
          "id": 2353,
          "name": "Emma Marie Umurerwa",
          "count": 2
        },
        {
          "slug": "umurerwa-emma-marie",
          "id": 633,
          "name": "Umurerwa Emma-marie",
          "count": 2
        },
        {
          "slug": "emma-marie-umurerwa-4",
          "id": 2311,
          "name": "Emma –Marie Umurerwa",
          "count": 1
        }
      ]
    },
    {
      "canonical": "joseph-curio",
      "canonicalId": 631,
      "name": "Joseph Curio",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "h-joseph-curio",
          "id": 433,
          "name": "H. Joseph Curio",
          "count": 1
        }
      ]
    },
    {
      "canonical": "kabagambe-rwiyemaho-ignatius",
      "canonicalId": 2999,
      "name": "Kabagambe Rwiyemaho Ignatius",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ignatius-rwiyemaho-kabagambe",
          "id": 3197,
          "name": "Ignatius Rwiyemaho Kabagambe",
          "count": 1
        }
      ]
    },
    {
      "canonical": "lin-hang",
      "canonicalId": 3118,
      "name": "Lin Hang",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ms-lin-hang",
          "id": 3121,
          "name": "Ms. LIN Hang",
          "count": 1
        }
      ]
    },
    {
      "canonical": "mail-guardian-africa",
      "canonicalId": 2584,
      "name": "Mail Guardian Africa",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "mailguardian-africa",
          "id": 2595,
          "name": "Mail&amp;Guardian Africa",
          "count": 1
        }
      ]
    },
    {
      "canonical": "marie-ange-mukaneza-3",
      "canonicalId": 2928,
      "name": "Marie-Ange Mukaneza",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "marie-ange-mukaneza",
          "id": 211,
          "name": "Marie Ange Mukaneza",
          "count": 1
        }
      ]
    },
    {
      "canonical": "munezero-ornella",
      "canonicalId": 582,
      "name": "Munezero Ornella",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ornella-munezero",
          "id": 581,
          "name": "Ornella Munezero",
          "count": 1
        }
      ]
    },
    {
      "canonical": "natasha-irigoga-charlotte",
      "canonicalId": 2357,
      "name": "Natasha Irigoga Charlotte",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "irigoga-charlotte-natasha",
          "id": 2366,
          "name": "Irigoga Charlotte Natasha",
          "count": 1
        },
        {
          "slug": "irigoga-natasha-charlotte",
          "id": 2365,
          "name": "Irigoga Natasha Charlotte",
          "count": 1
        }
      ]
    },
    {
      "canonical": "nkurunziza-faustin",
      "canonicalId": 595,
      "name": "Nkurunziza Faustin",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "faustin-nkurunziza",
          "id": 566,
          "name": "Faustin Nkurunziza",
          "count": 1
        }
      ]
    },
    {
      "canonical": "nytimes",
      "canonicalId": 2558,
      "name": "NYTIMES",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ny-times",
          "id": 2569,
          "name": "NY TIMES",
          "count": 1
        }
      ]
    },
    {
      "canonical": "rachel-mukandayisenga",
      "canonicalId": 414,
      "name": "Rachel Mukandayisenga",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "racheal-mukandayisenga",
          "id": 412,
          "name": "Racheal Mukandayisenga",
          "count": 1
        }
      ]
    },
    {
      "canonical": "rangira-bruno",
      "canonicalId": 353,
      "name": "Rangira Bruno",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "bruno-rangira",
          "id": 355,
          "name": "Bruno Rangira",
          "count": 1
        }
      ]
    },
    {
      "canonical": "sam-abdul-aziz-sewanyana-jr-3",
      "canonicalId": 3049,
      "name": "Sam Abdul Aziz Sewanyana-Jr",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "sam-abdul-aziz-sewanyana-jr",
          "id": 2994,
          "name": "Sam Abdul Aziz Sewanyana Jr",
          "count": 1
        }
      ]
    },
    {
      "canonical": "segun-ogunsanya",
      "canonicalId": 3092,
      "name": "Segun Ogunsanya",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dr-segun-ogunsanya",
          "id": 3120,
          "name": "Dr. Segun Ogunsanya",
          "count": 1
        }
      ]
    },
    {
      "canonical": "andrew-m-mwenda",
      "canonicalId": 2841,
      "name": "Andrew M. Mwenda",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "andrew-mwenda",
          "id": 217,
          "name": "Andrew Mwenda",
          "count": 0
        }
      ]
    },
    {
      "canonical": "ange-de-la-victoire-karirima-n",
      "canonicalId": 2282,
      "name": "Ange de la Victoire &amp; Karirima N.",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "ange-de-la-victoire-d-karirima-n",
          "id": 2317,
          "name": "Ange de la Victoire D. &amp; Karirima N.",
          "count": 1
        }
      ]
    },
    {
      "canonical": "ange-m-mukaneza",
      "canonicalId": 2898,
      "name": "Ange M. Mukaneza",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "mukaneza-m-ange",
          "id": 2934,
          "name": "Mukaneza M. Ange",
          "count": 1
        }
      ]
    },
    {
      "canonical": "bertin-ganza",
      "canonicalId": 3182,
      "name": "Bertin Ganza",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "bertin-k-ganza",
          "id": 3186,
          "name": "Bertin K. Ganza",
          "count": 1
        },
        {
          "slug": "ganza-k-bertin",
          "id": 272,
          "name": "Ganza K. Bertin",
          "count": 1
        }
      ]
    },
    {
      "canonical": "cyuzuzo-henriette",
      "canonicalId": 2373,
      "name": "Cyuzuzo.Henriette",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "cyuzuzo-henriette-3",
          "id": 2383,
          "name": "Cyuzuzo Henriette",
          "count": 1
        }
      ]
    },
    {
      "canonical": "diogene-bideri",
      "canonicalId": 584,
      "name": "Diogene Bideri",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dr-diogene-bideri",
          "id": 2351,
          "name": "Dr. Diogene Bideri",
          "count": 1
        }
      ]
    },
    {
      "canonical": "dr-pierre-damien-habumuremyi",
      "canonicalId": 207,
      "name": "Dr Pierre Damien Habumuremyi",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dr-pierre-damien-habumuremyi-3",
          "id": 2435,
          "name": "Dr Pierre-Damien Habumuremyi",
          "count": 1
        },
        {
          "slug": "dr-pierre-damien-habumuremyi-4",
          "id": 2449,
          "name": "Dr. Pierre Damien Habumuremyi",
          "count": 1
        }
      ]
    },
    {
      "canonical": "dr-twahirwa-setako-j",
      "canonicalId": 3146,
      "name": "Dr. Twahirwa Setako J",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "dr-twahirwa-setako",
          "id": 3145,
          "name": "Dr. Twahirwa Setako",
          "count": 0
        }
      ]
    },
    {
      "canonical": "dunyanews",
      "canonicalId": 2666,
      "name": "Dunyanews",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dunya-news",
          "id": 2673,
          "name": "Dunya News",
          "count": 1
        }
      ]
    },
    {
      "canonical": "elvis-nibomari",
      "canonicalId": 2325,
      "name": "Elvis Nibomari",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "nibomari-elvis",
          "id": 327,
          "name": "Nibomari Elvis",
          "count": 1
        }
      ]
    },
    {
      "canonical": "emmanuel-hategeka",
      "canonicalId": 3009,
      "name": "Emmanuel Hategeka",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "amb-emmanuel-hategeka",
          "id": 2995,
          "name": "Amb. Emmanuel Hategeka",
          "count": 1
        }
      ]
    },
    {
      "canonical": "eric-shaba",
      "canonicalId": 2393,
      "name": "Eric SHABA",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "erick-shaba",
          "id": 2367,
          "name": "Erick Shaba",
          "count": 1
        }
      ]
    },
    {
      "canonical": "erica-barks-ruggles",
      "canonicalId": 2862,
      "name": "Erica Barks-Ruggles",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "ambassador-erica-barks-ruggles",
          "id": 2428,
          "name": "Ambassador Erica Barks-Ruggles",
          "count": 1
        },
        {
          "slug": "by-erica-j-barks-ruggles",
          "id": 2494,
          "name": "By Erica J. Barks-Ruggles",
          "count": 1
        }
      ]
    },
    {
      "canonical": "fred-nkotanyi",
      "canonicalId": 2375,
      "name": "Fred Nkotanyi",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "nkotanyi-fred",
          "id": 2408,
          "name": "NKOTANYI FRED",
          "count": 0
        }
      ]
    },
    {
      "canonical": "gnnliberia",
      "canonicalId": 2606,
      "name": "Gnnliberia",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "gnn-liberia",
          "id": 2572,
          "name": "GNN Liberia",
          "count": 1
        }
      ]
    },
    {
      "canonical": "iradukunda-liliane",
      "canonicalId": 717,
      "name": "Iradukunda Liliane",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "liliane-iradukunda",
          "id": 3230,
          "name": "Liliane Iradukunda",
          "count": 1
        }
      ]
    },
    {
      "canonical": "jean-claude-mutajogire",
      "canonicalId": 2844,
      "name": "Jean Claude Mutajogire",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "jean-claude-mutajogire-3",
          "id": 2925,
          "name": "Jean-Claude Mutajogire",
          "count": 0
        }
      ]
    },
    {
      "canonical": "john-simpson",
      "canonicalId": 729,
      "name": "John Simpson",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "dr-john-simpson",
          "id": 728,
          "name": "Dr. John Simpson",
          "count": 0
        }
      ]
    },
    {
      "canonical": "kwizera-prudence",
      "canonicalId": 688,
      "name": "Kwizera Prudence",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "prudence-kwizera",
          "id": 683,
          "name": "Prudence Kwizera",
          "count": 1
        }
      ]
    },
    {
      "canonical": "lovepanky",
      "canonicalId": 2457,
      "name": "Lovepanky",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "love-panky",
          "id": 2464,
          "name": "Love Panky",
          "count": 1
        }
      ]
    },
    {
      "canonical": "macharia-kamau",
      "canonicalId": 634,
      "name": "Macharia Kamau",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "amb-macharia-kamau",
          "id": 264,
          "name": "Amb. Macharia Kamau",
          "count": 1
        }
      ]
    },
    {
      "canonical": "meilleur-murindabigwi",
      "canonicalId": 2372,
      "name": "Meilleur Murindabigwi",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "murindabigwi-meilleur",
          "id": 509,
          "name": "Murindabigwi Meilleur",
          "count": 1
        }
      ]
    },
    {
      "canonical": "mugabi-mukarage-stephen",
      "canonicalId": 447,
      "name": "Mugabi Mukarage Stephen",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "mugabi-mukaragi-stephen",
          "id": 2257,
          "name": "Mugabi Mukaragi Stephen",
          "count": 1
        }
      ]
    },
    {
      "canonical": "mutoni-queen",
      "canonicalId": 246,
      "name": "Mutoni Queen",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "queen-mutoni",
          "id": 2528,
          "name": "Queen Mutoni",
          "count": 1
        }
      ]
    },
    {
      "canonical": "radiotamazuj",
      "canonicalId": 2527,
      "name": "Radiotamazuj",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "radio-tamazuj",
          "id": 2745,
          "name": "Radio Tamazuj",
          "count": 1
        }
      ]
    },
    {
      "canonical": "rugasa-ruzindana",
      "canonicalId": 423,
      "name": "Rugasa Ruzindana",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "ruzindana-rugasa",
          "id": 418,
          "name": "Ruzindana RUGASA",
          "count": 1
        }
      ]
    },
    {
      "canonical": "sam-a-sewanyana-jr",
      "canonicalId": 3162,
      "name": "Sam A. Sewanyana-Jr",
      "confidence": "typo",
      "aliases": [
        {
          "slug": "sam-a-sewanyana-jnr",
          "id": 186,
          "name": "Sam A. Sewanyana, Jnr.",
          "count": 1
        }
      ]
    },
    {
      "canonical": "theculturetrip",
      "canonicalId": 2885,
      "name": "Theculturetrip",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "the-culturetrip",
          "id": 2890,
          "name": "The CultureTrip",
          "count": 1
        }
      ]
    },
    {
      "canonical": "thenairobian",
      "canonicalId": 2894,
      "name": "TheNairobian",
      "confidence": "exact",
      "aliases": [
        {
          "slug": "the-nairobian",
          "id": 2859,
          "name": "The Nairobian",
          "count": 1
        }
      ]
    }
  ]
}
